const zhCN = {
  // 通用
  common: {
    search: '搜索',
    submit: '提交',
    cancel: '取消',
    confirm: '确认',
    delete: '删除',
    edit: '编辑',
    save: '保存',
    loading: '加载中...',
    noData: '暂无数据',
    back: '返回',
    next: '下一步',
    previous: '上一步',
    close: '关闭',
    open: '打开',
    yes: '是',
    no: '否',
    error: '错误',
    success: '成功',
    warning: '警告',
    info: '信息',
    select: '选择',
    expand: '展开 ({count})',
    collapse: '收起',
    unknown: '未知',
    unknownCourse: '未知课程',
    unknownTeacher: '未知老师',
    unknownTime: '未知时间',
    clear: '清空',
    reset: '重置',
    confirmClear: '确认清空',
    cached: '已缓存',
    notCached: '未缓存'
  },

  // 导航
  navigation: {
    home: '首页',
    courses: '课程',
    search: '搜索',
    reviews: '评价',
    teachers: '教师',
    about: '关于',
    admin: '管理',
    login: '登录',
    logout: '退出登录',
    profile: '个人资料',
    settings: '设置'
  },

  // 首页
  home: {
    title: 'WHU.sb',
    subtitle: '发现最好的课程，分享你的学习体验',
    searchPlaceholder: '搜索课程、教师或关键词...',
    searchPlaceholderMobile: '搜索课程...',
    searchPlaceholderSmallMobile: '搜索...',
    searchButtonText: '搜索',
    searchButtonMobile: '搜索',
    searchButtonSmallMobile: '搜索',
    addReviewButtonText: '添加评价',
    addReviewButtonMobile: '添加',
    luckyButton: '手气不错',
    luckyButtonMobile: '手气不错',
    popularCourses: '热门课程',
    recentReviews: '最新评价',
    topTeachers: '优秀教师',
    welcomeMessage: '欢迎使用武汉大学课程评价系统',
    getStarted: '开始使用',
    learnMore: '了解更多'
  },

  // 课程相关
  courses: {
    title: '课程列表',
    subtitle: '发现适合你的课程',
    startSearch: '开始搜索课程',
    searchHint: '使用上方的搜索框查找你感兴趣的课程',
    courseDetail: '课程详情',
    courseName: '课程名称',
    courseCode: '课程代码',
    credits: '学分',
    department: '开课院系',
    semester: '学期',
    teacher: '授课教师',
    rating: '评分',
    reviewCount: '评价数量',
    difficulty: '难度',
    workload: '工作量',
    recommendation: '推荐度',
    addReview: '添加评价',
    viewReviews: '查看评价',
    noCoursesFound: '未找到相关课程',
    filterBy: '按条件筛选',
    sortBy: '排序方式',
    sortByRating: '按评分排序',
    sortByReviewCount: '按评价数量排序',
    sortByName: '按名称排序',
    backToCourse: '返回课程',
    teachers: '授课教师',
    teachersHint: '（点击教师名字进入课程讲师档案）',
    loadingTeachers: '加载教师信息...',
    fetchTeachersError: '获取教师信息失败'
  },

  // 评价相关
  reviews: {
    title: '课程评价',
    addReview: '添加评价',
    editReview: '编辑评价',
    reviewDetail: '评价详情',
    rating: '评分',
    content: '评价内容',
    difficulty: '课程难度',
    workload: '工作量',
    recommendation: '推荐度',
    semester: '学期',
    anonymous: '匿名发布',
    submitReview: '提交评价',
    updateReview: '更新评价',
    deleteReview: '删除评价',
    confirmDelete: '确认删除此评价？',
    noReviews: '暂无评价',
    helpful: '有帮助',
    report: '举报',
    reply: '回复',
    like: '点赞',
    unlike: '取消点赞',
    reviewHelpful: '此评价对您有帮助吗？',
    reviewReported: '评价已举报',
    reviewSubmitted: '评价提交成功',
    reviewUpdated: '评价更新成功',
    reviewDeleted: '评价删除成功',
    reviewContent: '评价内容',
    clickToViewFull: '点击查看完整评价',
    tags: '标签',
    grade: '成绩',
    detailedRatings: '详细评分',
    veryEasy: '很简单',
    veryHard: '很困难',
    veryLittle: '很少',
    veryMuch: '很多',
    veryPoor: '很差',
    veryGood: '很好',
    veryBoring: '很枯燥',
    veryInteresting: '很有趣',
    easy: '简单',
    moderate: '适中',
    hard: '困难',
    light: '轻松',
    heavy: '繁重',
    veryLight: '很轻松',
    veryHeavy: '很繁重',
    poor: '较差',
    fair: '一般',
    good: '良好',
    excellent: '优秀',
    boring: '无聊',
    interesting: '有趣',
    notRated: '未评价',
    viewAllReviews: '查看全部评价',
    beFirstReview: '成为第一个评价这门课程的人！'
  },

  // 教师相关
  teachers: {
    title: '教师列表',
    teacherDetail: '教师详情',
    teacherName: '教师姓名',
    department: '所属院系',
    teacherTitle: '职称',
    courses: '授课课程',
    averageRating: '平均评分',
    reviewCount: '评价数量',
    noTeachersFound: '未找到相关教师',
    viewCourses: '查看课程',
    contactInfo: '联系方式',
    research: '研究方向',
    education: '教育背景',
    relatedCourses: '相关课程',
    courseCount: '课程数',
    teachingQuality: '教学质量',
    courseDifficulty: '课程难度',
    homeworkLoad: '作业量',
    courseInterest: '课程趣味性'
  },

  // 搜索
  search: {
    title: '搜索结果',
    subtitle: '查找你感兴趣的课程',
    simpleSearch: '简单搜索',
    simple: '简单',
    switchToSimple: '切换到简单搜索',
    advancedFilter: '高级筛选',
    advanced: '高级',
    switchToAdvanced: '切换到高级筛选',
    queryBuilder: '查询构建器',
    builder: '构建器',
    switchToBuilder: '切换到查询构建器',
    addCourseReview: '添加课程评价',
    placeholder: '搜索课程、教师或关键词...',
    searchCourses: '搜索课程...',
    advancedSearch: '高级搜索',
    searchResults: '搜索结果',
    noResults: '未找到相关结果',
    searchFilters: '搜索筛选',
    keyword: '关键词',
    department: '院系',
    semester: '学期',
    rating: '评分',
    difficulty: '难度',
    workload: '工作量',
    clearFilters: '清除筛选',
    applyFilters: '应用筛选',
    advancedSearchOptions: '高级搜索选项',
    courseInfo: '课程信息',
    enterCourseName: '输入课程名称',
    enterTeacherName: '输入老师姓名',
    courseAttribute: '课程属性',
    selectCourseAttribute: '选择课程属性',
    selectCredits: '选择学分',
    electiveOptions: '公选课选项',
    electiveField: '公选课领域',
    selectElectiveField: '选择公选课领域',
    assessmentMethod: '考核方式',
    finalExamMethod: '期末考核方式',
    selectExamMethod: '选择考核方式',
    attendanceAndHomework: '考勤与平时作业',
    describeAttendancePolicy: '描述考勤和作业要求...',
    courseContent: '课程内容',
    courseContentAndEvaluation: '课程内容与评价',
    describeCourseContent: '描述课程内容、教学方式等...',
    advancedSearchSyntax: '高级搜索语法',
    clearConditions: '清空条件',
    advancedQueryBuilder: '高级查询构建器',
    addCondition: '添加条件',
    addGroup: '添加分组',
    groupStart: '分组开始',
    deleteGroup: '删除分组',
    groupOperator: '分组操作符',
    clickAddConditionOrGroup: '点击"添加条件"或"添加分组"开始构建查询',
    addConditionTip: '添加条件：创建单个搜索条件',
    addGroupTip: '添加分组：创建括号分组（前括号、操作符、后括号）',
    dragTip: '拖拽功能：点击并拖动左侧的条形图标来改变条件顺序或移入分组',
    generatedQuery: '生成的查询语法',
    copyQuery: '复制查询语法',
    syntaxExplanation: '语法说明',
    andExample: 'A AND B',
    andExplanation: 'A和B都必须满足',
    orExample: 'A OR B',
    orExplanation: 'A或B满足其一即可',
    parenthesesExample: '(A AND B) OR C',
    parenthesesExplanation: 'A和B都满足，或者C满足',
    parenthesesExample2: 'A AND (B OR C)',
    parenthesesExplanation2: 'A必须满足，且B或C满足其一',
    applyQuery: '应用查询',
    confirmClearQuery: '确认清空查询',
    confirmClearQueryMessage: '确定要清空所有查询条件吗？此操作不可撤销。',
    and: 'AND',
    or: 'OR',
    courseName: '课程名称',
    professor: '授课教师',
    courseType: '课程类型',
    credits: '学分',
    examMethod: '考核方式',
    description: '课程描述',
    contains: '包含',
    exactMatch: '精确匹配',
    startsWith: '开头匹配',
    endsWith: '结尾匹配',
    equals: '等于',
    notEquals: '不等于',
    greaterThan: '大于',
    lessThan: '小于',
    greaterEqual: '大于等于',
    lessEqual: '小于等于',
    notContains: '不包含',
    cleared: '已清空',
    allConditionsCleared: '所有查询条件已清空',
    copied: '复制成功',
    querySyntaxCopied: '查询语法已复制到剪贴板',
    copyFailed: '复制失败',
    courseSearch: '课程搜索',
    searchCourseNameTeacherCode: '搜索课程名称、教师或课程代码...',
    collapseAdvancedSearch: '收起高级搜索',
    expandAdvancedSearch: '展开高级搜索',
    teacherName: '教师姓名',
    selectDepartment: '选择院系',
    selectCourseType: '选择课程类型',
    creditsNumber: '学分数'
  },

  // 关于页面
  about: {
    title: '关于我们',
    subtitle: '欢迎来到 WhuSB - 武汉大学课程评价平台！'
  },

  // 错误页面
  error: {
    teapot: {
      title: 'I\'m a Teapot',
      message1: '我是一个茶壶，不能煮咖啡。',
      message2: '这个HTTP状态码是1998年愚人节的笑话，但现在已经正式成为HTTP标准的一部分。',
      knowledge: {
        title: '🍵 茶壶小知识',
        p1: 'HTTP 418 "I\'m a Teapot" 最初是1998年愚人节的笑话，由RFC 2324定义。',
        p2: '它表示服务器拒绝尝试用茶壶煮咖啡，因为茶壶只能用来泡茶。',
        p3: '2014年，这个状态码被正式收录到HTTP标准中。'
      }
    }
  },

  // 用户相关
  user: {
    profile: '个人资料',
    settings: '设置',
    myReviews: '我的评价',
    myCourses: '我的课程',
    favorites: '收藏',
    notifications: '通知',
    changePassword: '修改密码',
    logout: '退出登录',
    login: '登录',
    register: '注册',
    username: '用户名',
    email: '邮箱',
    password: '密码',
    confirmPassword: '确认密码',
    forgotPassword: '忘记密码',
    rememberMe: '记住我',
    loginSuccess: '登录成功',
    logoutSuccess: '退出成功',
    profileUpdated: '个人资料更新成功'
  },

  // 管理后台
  admin: {
    title: '管理后台',
    dashboard: '仪表板',
    users: '用户管理',
    courses: '课程管理',
    reviews: '评价管理',
    logs: '系统日志',
    settings: '系统设置',
    statistics: '统计信息',
    userCount: '用户数量',
    courseCount: '课程数量',
    reviewCount: '评价数量',
    todayVisits: '今日访问',
    totalVisits: '总访问量',
    systemStatus: '系统状态',
    online: '在线',
    offline: '离线',
    maintenance: '维护中'
  },

  // 错误页面
  errors: {
    notFound: '页面未找到',
    notFoundMessage: '抱歉，您访问的页面不存在',
    serverError: '服务器错误',
    serverErrorMessage: '抱歉，服务器出现了问题',
    unauthorized: '未授权访问',
    unauthorizedMessage: '您没有权限访问此页面',
    forbidden: '禁止访问',
    forbiddenMessage: '您被禁止访问此页面',
    goHome: '返回首页',
    goBack: '返回上页',
    retry: '重试'
  },

  // 表单验证
  validation: {
    required: '此字段为必填项',
    email: '请输入有效的邮箱地址',
    minLength: '最少需要 {min} 个字符',
    maxLength: '最多允许 {max} 个字符',
    passwordMatch: '两次输入的密码不一致',
    invalidFormat: '格式不正确',
    numberRange: '数值必须在 {min} 到 {max} 之间'
  },

  // 时间相关
  time: {
    justNow: '刚刚',
    minutesAgo: '{minutes} 分钟前',
    hoursAgo: '{hours} 小时前',
    daysAgo: '{days} 天前',
    weeksAgo: '{weeks} 周前',
    monthsAgo: '{months} 个月前',
    yearsAgo: '{years} 年前',
    today: '今天',
    yesterday: '昨天',
    tomorrow: '明天'
  },

  // 主题相关
  theme: {
    light: '浅色',
    dark: '深色',
    auto: '自动',
    lightTheme: '浅色主题',
    darkTheme: '深色主题',
    autoTheme: '自动主题',
    switchTheme: '切换主题'
  },

  // 分页
  pagination: {
    navigation: '分页导航',
    previous: '上一页',
    next: '下一页',
    page: '第 {page} 页',
    of: '共 {total} 页',
    showing: '显示第 {start} 到 {end} 条，共 {total} 条'
  }
}

export default zhCN 